// @flow

export default {
  'personal-training-exercise': [
    {
      label: 'Muscle Group',
      name: 'muscleGroup',
      type: 'multipleChoice',
      choices: [
        { label: 'Traps', value: 'traps' },
        { label: 'Shoulders', value: 'shoulders' },
        { label: 'Chest', value: 'chest' },
        { label: 'Biceps', value: 'biceps' },
        { label: 'Abdominals', value: 'abdominals' },
        { label: 'Forearms', value: 'forearms' },
        { label: 'Quads', value: 'quads' },
        { label: 'Calves', value: 'calves' },
        { label: 'Traps-middle', value: 'traps-middle' },
        { label: 'Lats', value: 'lats' },
        { label: 'Triceps', value: 'triceps' },
        { label: 'Lowerback', value: 'lowerback' },
        { label: 'Glutes', value: 'glutes' },
        { label: 'Hamstrings', value: 'hamstrings' },
      ],
    },
    {
      label: 'Exercise Type',
      name: 'exerciseType',
      type: 'multipleChoice',
      choices: [
        { label: 'Bodyweight', value: 'bodyweight' },
        { label: 'Exercises', value: 'exercise' },
        { label: 'Stretches', value: 'stretch' },
      ],
    },
    {
      label: 'Gender',
      name: 'gender',
      type: 'multipleChoice',
      choices: [{ label: 'Male', value: 'male' }, { label: 'Female', value: 'female' }],
    },
  ],
  'personal-training-habit': [
    {
      label: 'Habit Type',
      name: 'habitType',
      type: 'multipleChoice',
      choices: [
        { label: 'Record what you eat', value: 'record what you eat' },
        { label: 'Eat every 3-4 hours', value: 'eat every 3-4 hours' },
        { label: 'Eat protein', value: 'eat protein' },
        { label: 'Eat Vegetables', value: 'eat vegetables' },
        { label: 'Watch Carbs', value: 'watch carbs' },
        { label: 'Watch Fats', value: 'watch fats' },
        { label: 'Watch Water', value: 'watch water' },
        { label: 'Watch Sleep', value: 'watch sleep' },
        { label: 'Watch Single', value: 'watch single' },
        { label: 'Gut Stress', value: 'gut stress' },
      ],
    },
    {
      label: 'Day',
      name: 'day',
      type: 'multipleChoice',
      choices: [
        { label: 'Day 1', value: 'day 1' },
        { label: 'Day 2', value: 'day 2' },
        { label: 'Day 3', value: 'day 3' },
        { label: 'Day 4', value: 'day 4' },
        { label: 'Day 5', value: 'day 5' },
        { label: 'Day 6', value: 'day 6' },
        { label: 'Day 7', value: 'day 7' },
        { label: 'Day 8', value: 'day 8' },
        { label: 'Day 9', value: 'day 9' },
        { label: 'Day 10', value: 'day 10' },
        { label: 'Day 11', value: 'day 11' },
        { label: 'Day 12', value: 'day 12' },
        { label: 'Day 13', value: 'day 13' },
        { label: 'Day 14', value: 'day 14' },
      ],
    },
  ],
  'personal-training-recipe': [
    {
      label: 'Recipes',
      name: 'recipeType',
      type: 'multipleChoice',
      choices: [
        { label: 'Gluten Free', value: 'gluten free' },
        { label: 'Dairy Free', value: 'dairy free' },
        { label: 'Low Carb (under 20g serving)', value: 'low carb (under 20g per serving)' },
        { label: 'Meal Prep/Freezer Friendly', value: 'meal prep/freezer friendly' },
        { label: 'High Protein', value: 'high protein' },
        { label: 'Vegetarian', value: 'vegetarian' },
        { label: 'Quick (under 30 mins)', value: 'quick (under 30 mins)' },
        { label: 'Contains Nuts', value: 'contains nuts' },
        { label: 'Breakfast', value: 'breakfast' },
      ],
    },
    {
      label: 'Meal Type',
      name: 'mealType',
      type: 'multipleChoice',
      choices: [
        { label: 'Breakfast', value: 'breakfast' },
        { label: 'Lunch', value: 'lunch' },
        { label: 'Dinner', value: 'dinner' },
        { label: 'Snack', value: 'snack' },
      ],
    },
  ],
};
